name: axisem3d_output
channels:
  - conda-forge
  - anaconda
dependencies:
  - # This file may be used to create an environment using:
  - # $ conda create --name <env> --file <this file>
  - # platform: linux-64