name: Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    strategy:
        fail-fast: false
        matrix: 
            os: [ubuntu-latest]
            python-version:
                - "3.9"

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            conda create --name test --file requirements.txt -c conda-forge
            conda run --name test conda install -c conda-forge coverage

        - name: Run tests with coverage
          run: |
            conda run --name test coverage run --source axisem3d_output -m pytest
            conda run --name test coverage report -m

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v3
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            file: coverage.xml
            
